### ISSUE TITLE
Display next and previous transaction

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/mvs-explorer-www#16]
In the transaction page, for each input, give a link to the previous output
For each output, say if it is spent or not. If it is, give a link to next transaction

**Comment by LaurentSalou** [comment]
Done on front-end side in commit c08f6b9
It already works for inputs, but we need to update the sync script to have it for outputs (spent_tx is currently always at 0)

**Comment by LaurentSalou** [comment]
also work for outputs after updating the api
