### ISSUE TITLE
Add output type in transaction page

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/mvs-explorer-www#20]
If the output is an avatar issue, MIT creation etc... add the type of transaction.

Type can also be indicated with icon from issue #19

**Comment by LaurentSalou** [comment]
Done, it detects the following types:
- "MIT Creation"
- "MIT Transfer"
- "New Avatar"
- "Avatar transfer"
- "Asset issue"
- "Asset Secondary Issue"
- "Secondary Issue certificate"
- "Domain certificate"
- "Naming certificate"

Icons were too much to add, especially for big transaction, so it only shows the above text
